### ISSUE TITLE
Changes in grid origin

### ISSUE THREAD

**Issue by nutrik** [dionhaefner/veros#32]
Hi Dion,
When I change `x_origin` of Veros grid (91. --> 181.) in `setup/global_1deg/global_one_degree.py`, the resulted Land mass and perimeter (see below) contain New Zealand as a lake area (or sea) and the model returns the following:
```
/groups/ocean/software/bohrium/gcc/14112017/lib64/python2.7/site-packages/bohrium/array_create.py:167: RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  return numpy.array(ary, dtype=dtype, copy=copy, order=order, subok=subok, ndmin=ndmin, fix_biclass=False)
/lustre/hpc/ocean/nutrik/veros/veros/core/external/solve_poisson.py:75: RuntimeWarning: divide by zero encountered in divide
  Z[2:-2, 2:-2] = np.where(Y != 0., 1. / Y, 1.)
Traceback (most recent call last):
  File "global_one_degree.py", line 273, in <module>
    simulation.setup()
  File "/lustre/hpc/ocean/nutrik/veros/veros/veros.py", line 234, in setup
    external.streamfunction_init(self)
  File "/lustre/hpc/ocean/nutrik/veros/veros/decorators.py", line 50, in veros_method_wrapper
    res = function(*args, **kwargs)
  File "/lustre/hpc/ocean/nutrik/veros/veros/core/external/streamfunction_init.py", line 166, in streamfunction_init
    solve_poisson.initialize_solver(vs)
  File "/lustre/hpc/ocean/nutrik/veros/veros/decorators.py", line 50, in veros_method_wrapper
    res = function(*args, **kwargs)
  File "/lustre/hpc/ocean/nutrik/veros/veros/core/external/solve_poisson.py", line 18, in initialize_solver
    preconditioner = _jacobi_preconditioner(vs, matrix)
  File "/lustre/hpc/ocean/nutrik/veros/veros/decorators.py", line 50, in veros_method_wrapper
    res = function(*args, **kwargs)
  File "/lustre/hpc/ocean/nutrik/veros/veros/core/external/solve_poisson.py", line 76, in _jacobi_preconditioner
    return scipy.sparse.dia_matrix((Z.flatten(), 0), shape=(Z.size, Z.size)).tocsr()
  File "/groups/ocean/software/python/gcc/2.7.13/lib/python2.7/site-packages/scipy/sparse/base.py", line 764, in tocsr
    return self.tocoo(copy=copy).tocsr(copy=False)
  File "/groups/ocean/software/python/gcc/2.7.13/lib/python2.7/site-packages/scipy/sparse/dia.py", line 354, in tocoo
    mask &= (self.data != 0)
  File "ufuncs.pyx", line 594, in ufuncs._handle__array_ufunc__ (/groups/ocean/software/tarballs/bohrium/bohrium14112017/build/bridge/npbackend/ufuncs.c:12150)
  File "bhary.pyx", line 105, in bhary.fix_biclass_wrapper.inner (/groups/ocean/software/tarballs/bohrium/bohrium14112017/build/bridge/npbackend/bhary.c:3381)
  File "ufuncs.pyx", line 161, in ufuncs.Ufunc.__call__ (/groups/ocean/software/tarballs/bohrium/bohrium14112017/build/bridge/npbackend/ufuncs.c:5755)
AttributeError: 'tuple' object has no attribute 'shape'
```
Similar story happens to the `setup/wave_propagation` case or the model cannot initialise barotropic stream function solver and returns the following error:
```
  File "..../veros/core/external/streamfunction_init.py", line 69, in streamfunction_init
    raise RuntimeError("found no starting point for line integral")
```
Do you know how algorithms for "Land mass and perimeter" setup +  streamfunction_init work?

```
                                                      Land mass and perimeter

    0    5   10   15   20   25   30   35   40   45   50   55   60   65   70   75   80   85   90   95  100  105  110  115  120
163 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
162 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
161 ****1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
160 000*******1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
159 000*2********1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
158 *******1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
157 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
156 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
155 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
154 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
153 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
152 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
151 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
150 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
149 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
148 111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111*1111111111111111111111
147 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111*11111111***111111111111111111111
146 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111*****11******11111111111111111111
145 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111**000*****66****111111111111111111
144 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111*0000000******1111111111111111111
143 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111*******00000000000*11111111111111111111
142 11111111111111111111111111111111111111111111111111111111111111111111****11111111111****00000000000000000*11111111111111111111
141 1111111111111111111111111111111111111111111111111111111111111111111**0**11111*******00000000000000000000****11111111111111***
140 111111111111111111111111111111111111111111111111111111*****************11111**00000000000000000000000000000***1111111111***00
139 1111111111111111111111111111111111111111111111111111***000000000000**111111**00000000000000000000000000000000****1111111*0000
138 11111111111111111111111111111111111111111111111111***0000000000000**1111111*00000000000000000000000000000000****111**1***0000
137 1111111111111111111111111111111111111111111111111**000000000000000*1111111**00000000000000000000000000000****1111******000000
136 11111111111111111111111111111111111111111111111111******0000000000*1111111*00000000000000000000000000000**1111****00000000000
135 1111111111111111111111111111111111111111111111111111111*0000000000**1111***00000000000000000000000000000*1*****00000000000000
134 1111111111111111111111111111111111111111111111111111111**0000000000*111**0000000000000000000000000000000***000000000000000000
133 11111111111111111111111111111111111111111111111111111111*0000000000*11**00000000000000000000000000000000000000000000000000000
132 11111111111111111111111111111111111111111111111111111*11*0000000000****000000000000000000000000000000000000000000000000000000
131 11111111111111111111111111111111111111111111111111111*11*00000000000000000000000000000000000000000000000000000000000000000000
130 1111111111111111111111111111111111111111111111111111**1**00000000000000000000000000000000000000000000000000000000000000000000
129 111111111111111111111111111111111111111111111111111*****000000000000000000000000000000000000000000000000000000000000000000000
128 111111111111111111111111111111111111111111111111111****0000000000000000000000000000000000000000000000000000000000000000000000
127 11111111111111111111111111111111111111111111111111***8***00000000000000000000000000000000000000000000000000000000000000000000
126 1111111111111111111111111111111111111111111111111**0*888****00000000000000000000000000000000000000000000000000000000000000000
125 11111111111111111111111111111111111111111111111***0**888888*00000000000000000000000000000000000000000000000000000000000000000
124 1111111111111111111111111111111111111111111*****000*8888****00000000000000000000000000000000000000000000000000000000000000000
123 111111111111111111111111111111111111111111**0000000*8****00000000000000000000000000000000000000000000000000000000000000000000
122 11111111111111111111111111111111111111111**00000000*88*0000000000000000000000000000000000000000000000000000000000000000000000
121 1111111111111111111111111111111111111111**00000000**88*0000000000000000000000000000000000000000000000000000000000000000000000
120 1111111111111111111111111111111111111111**00000****888*0000000000000000000000000000000000000000000000000000000000000000000000
119 11111111111111111111111111111111111***111**0000*8*888**0000000000000000000000000000000000000000000000000000000000000000000000
118 1111111111111111111111111111111111**0*1111******88888*00000000000000000000000000000000000000000000000000000000000000000000000
117 111111111111111111111111111111111**00*111***888888888*00000000000000000000000000000000000000000000000000000000000000000000000
116 111111111111111111111111111111111*000*111**888888*****00000000000000000000000000000000000000000000000000000000000000000000000
115 111111111111111111111111111111111**00*1***88888***000000000000000000000000000000000000000000000000000000000000000000000000000
114 1111111111111111111111111111111111*00****888****00000000000000000000000000000000000000000000000000000000000000000000000000000
113 1111111111111111111111111111111111*00000**8**00000000000000000000000000000000000000000000000000000000000000000000000000000000
112 1111111111111111111111111111111111*000000***000000000000000000000000000000000000000000000000000000000000000000000000000000000
111 1111111111111111111111111111111111*000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
110 1111111111111111111111111111111111*000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
109 111111111111111111111111111111111**000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
108 11111111111111111111111111111111**0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
107 11111111111111111111111111111111***000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
106 1111111111111111111111111111111*11*000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
105 111111111111111111111111111111**1**000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
104 111111111111111111111111111*****1*0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
103 1111111111111111111111111***000***0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
102 ****111111111111111**11***00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000***0000000
101 000**1111111111111**111*00000000***00000000000000000000000000000000000000000000000000000000000000000000000000000000*4*0000000
100 0000**111111111111**11**0000000**6*00000000000000000000000000000000000000000000000000000000000000000000000000000000***0000000
 99 00000*1111111111111****00000000*66*000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 98 00000*11111111111111**000000000*66*000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 97 00000***1111111111111*000000000*66*000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 96 0000000***11111111111*000000000*66***0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 95 000000000*11111111111*000000000*6666*0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 94 000000000*11*11111111*000000000******0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 93 000000000*11***111111*00000000**7*8**0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 92 000000000*11*0*11111**0000000**7**88**000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 91 000000000*11*0**111**0000000**7*****8**00000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 90 000000000*11**0**1**00000000*7**0***88*00000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 89 000000000**11**0***00000000**7*00*8888*00000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 88 000000***0*111**0000000000**77**0***8**00000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 87 000000*1****111**00000000**7777*000***000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 86 000000*111**1111*0000000**77777*000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 85 000000***1111111*00000***77777**000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 84 00000000*1111111*000***7777777**0000000***00000000000000000000000000000000000000000000000000000000000000000000000000000000000
 83 00000000**111111*000*7777777777*******0*9*00000000000000000000000000000000000000000000000000000000000000000000000000000000000
 82 00000000*1*11111**00*777777777***0000*****00000000000000000000000000000000000000000000000000000000000000000000000000000000000
 81 00000000****11111*00*77777777***0******1*******000000000000000000000000000000000000000000000000000000000000000000000000000000
 80 00000000000*11111*****7777777**0000*00****2222*******000000000000000000000000000000000000000000000000000000000000000000000000
 79 00000000000**1111111**7777777**000**0*******22222222****000000000000000000000000000000000000000000000000000000000000000000000
 78 000000000000**1111*1***777777**0*00*0*3*444*22222222222***00000***00000000000000000000000000000000000000000000000000000000000
 77 0000000000000**111***0****77***0**0*0********2*2222222222**00***5***000000000000000000000000000000000000000000000000000000000
 76 00000000000000**11******0****0*0**0*00000000******22222222****55**7**00000000000000000000000000000000000000000000000000000000
 75 000000000000000**1111*1****000******000000****8*0*2222222222*******7*00000000000000000000000000000000000000000000000000000000
 74 0000000000000000***1111111*****00000000000*9****0*222222222**00000***0***0000000000000000000000000000000000000000000000000000
 73 000000000000000000*********000*0000***0000***0000***2222**22**00000000*1**000000000000000000000000000000000000000000000000000
 72 00000000000000000000000000*****000**2*0000000000000**222***22**0000000*11*000000000000000000000000000000000000000000000000000
 71 0000000000000000000000000000000000*2**000*****000000**22*0***2*0000000****000000000000000000000000000000000000000000000000000
 70 0000000000000000000000000000000000***0000*222*****000*22*000***00000000000000000000000000000000000000000000000000000000000000
 69 00000000000000000000000000000000000000000*2222222*00**22*00000000000000000000000000000000000000000000000000000000000000000000
 68 000000000000000000000000000000000000******2222222*00*222**0000000000000000000000000000000000000000000000000000000000000000000
 67 00000000000000000000000000000000000**222222222222*00*2222*0000000000000000000000000000000000000000000000000000000000000000000
 66 0000000000000000000000000000000000**2222222222222****2222**0000000000000000000000000000000***00000000000000000000000000000000
 65 000000000000000000000000000000000**22222222222222222*22222*00000000000000000000000000000***6*00000000000000000000000000000000
 64 000000000000000000000000000000000*222222222222222222222222**0000000000000000000000000000*7***00000000000000000000000000000000
 63 00000000000000000000000000000000**2222222222222222222222222***0000000***00***00000000000***0000000000000000000000000000000000
 62 00000000000000000000000000000****2222222222222222222222222222**000000*8*00*9**00000000000000000000000000000000000000000000000
 61 00000000000000000000000000****22222222222222222222222222222222**00000*8*00**9**0000000000000000000000000000000000000000000000
 60 0000000000000000000000000**222222222222222222222222222222222222*00000***000**9**000000000000000000000000000000000000000000000
 59 0000000000000000000000000*2222222222222222222222222222222222222*000000000000**9*000000000000000000000000000000000000000000000
 58 0000000000000000000000000*2222222222222222222222222222222222222***00000000000***000000000000000000000000000000000000000000000
 57 000000000000000000000000**222222222222222222222222222222222222222*00000000000000000000000000000000000000000000000000000000000
 56 000000000000000000000000*2222222222222222222222222222222222222222*00000000000000000000000000000000000000000000000000000000000
 55 000000000000000000000000*2222222222222222222222222222222222222222**0000000000000000000000000000000000000000000000000000000000
 54 000000000000000000000000**2222222222222222222222222222222222222222*0000000000000000000000000000000000000000000000000000000000
 53 0000000000000000000000000*2222222222222222222222222222222222222222*0000000000000000000000000000000000000000000000000000000000
 52 0000000000000000000000000**222222222222222222222222222222222222222*0000000000000000000000000000000000000000000000000000000000
 51 00000000000000000000000000*22222222222222222222222222222222222222**0000000000000000000000000000000000000000000000000000000000
 50 00000000000000000000000000*22222222222222222222222222222222222222*00000000000000000000000000000000000000000000000000000000000
 49 00000000000000000000000000*22222222222*******2222222222222222222**00000000000000000000000000000000000000000000000000000000000
 48 00000000000000000000000000*2222222222**00000**222222222222222222*000000000000000000000000000000000000000000000000000000000000
 47 00000000000000000000000000*2222*******0000000**2222222222222222**0000000000000000000****0000000000000000000000000000000000000
 46 00000000000000000000000000******00000000000000*2*22222222222222*00000000000000000000*00**000000000000000000000000000000000000
 45 0000000000000000000000000000000000000000000000****2*2222222222**00000000000000000000**00*000000000000000000000000000000000000
 44 0000000000000000000000000000000000000000000000000***2222222222*0000000000000000000000*00***0000000000000000000000000000000000
 43 000000000000000000000000000000000000000000000000000**2222222***000000000000000000000**0000*0000000000000000000000000000000000
 42 0000000000000000000000000000000000000000000000000000***2*****00000000000000000000000*0000**0000000000000000000000000000000000
 41 000000000000000000000000000000000000000000000000000000*******0000000000000000000000**0000*00000000000000000000000000000000000
 40 0000000000000000000000000000000000000000000000000000000*2222*000000000000000000000**000***00000000000000000000000000000000000
 39 0000000000000000000000000000000000000000000000000000000**222*0000000000000000000***000**0000000000000000000000000000000000000
 38 00000000000000000000000000000000000000000000000000000000**2**000000000000000000**0000**00000000000000000000000000000000000000
 37 000000000000000000000000000000000000000000000000000000000***000000000000000000**0000**000000000000000000000000000000000000000
 36 000000000000000000000000000000000000000000000000000000000000000000000000000000*0000**0000000000000000000000000000000000000000
 35 000000000000000000000000000000000000000000000000000000000000000000000000000000*000**00000000000000000000000000000000000000000
 34 000000000000000000000000000000000000000000000000000000000000000000000000000000*0***000000000000000000000000000000000000000000
 33 000000000000000000000000000000000000000000000000000000000000000000000000000000***00000000000000000000000000000000000000000000
 32 00000000000000000000000000000000000000000000000000000000000000000000000000000***000000000000000000000000000000000000000000000
 31 00000000000000000000000000000000000000000000000000000000000000000000000000000*5*000000000000000000000000000000000000000000000
 30 00000000000000000000000000000000000000000000000000000000000000000000000000000***000000000000000000000000000000000000000000000
 29 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 28 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 27 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 26 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 25 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 24 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 23 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 22 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 21 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 20 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 19 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 18 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 17 000000000000000000000000000000000000000000000***00000000000000000000000000000000000000000000000000000000000000000000000000000
 16 ********************0*******0000000*****0*****8******000000000000000000000000000000000000000000000000000000000000000000000000
 15 8**8888888888888888***88888*********888***8888888888*******000000000000000000000000000000000000000000000000000000000000000000
 14 8888888888888888888888888888888888888888888888888888888888******0000000000000000000000000000000000000000000000000000000000000
 13 888888888888888888888888888888888888888888888888888888888888888**********0000000000000000000000000000000000000000000000000000
 12 888888888888888888888888888888888888888888888888888888888888888888888888********000000000000000000000000000000000000000000000
 11 8888888888888888888888888888888888888888888888888888888888888888888888888888888*****00000000000000000000000000000000000000000
 10 88888888888888888888888888888888888888888888888888888888888888888888888888888888888*00000000000000000000000000000000000000000
  9 8888888888888888888888888888888888888888888888888888888888888888888888888888888888**00000000000000000000000000000000000000000
  8 888888888888888888888888888888888888888888888888888888888888888888888888888888888**000000000000000000000000000000000000000000
  7 88888888888888888888888888888888888888888888888888888888888888888888888888888*****0000000000000000000000000000000000000000000
  6 888888888888888888888888888888888888888888888888888888888888888888888888888***0000000000000000000000000000000000000000000****
  5 888888888888888888888888888888888888888888888888888888888888888888888888888***00000000000000000000000000000000000*********888
  4 88888888888888888888888888888888888888888888888888888888888888888888888888888*************************************88888888888
  3 88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
  2 88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
  1 88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
  0 88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
    0    5   10   15   20   25   30   35   40   45   50   55   60   65   70   75   80   85   90   95  100  105  110  115  120
```

**Comment by dionhaefner** [comment]
There are 3 different issues at play here.

1. New Zealand is not really classified as water here, it just gets the index `10` which is truncated to `0`.
2. The error thrown by Bohrium could be https://github.com/bh107/bohrium/issues/476, so it might be worth updating both Bohrium and Veros
3. This one is actually a critical error during grid setup that is hard to debug and depends a lot on the geometry at hand. Have you tried -180 instead of 181? That way you get a grid from -180 to 180, which sounds saner than one from 180 to 540.

**Comment by dionhaefner** [comment]
Note that I have an open issue for the cumbersome grid creation, #27. I just need to find a solution that works for both PyOM and Veros.

**Comment by nutrik** [comment]
Thanks Dion!
You are right, issue 2 disappeared when I used a new Bohrium!
The issue 3 has somehow vanished as well when I shifted the grid origin to -79 and 179. 
I will try more different combinations later :)

**Comment by dionhaefner** [comment]
This works fine now.
