### ISSUE TITLE
only acc and eady example setups work for me

### ISSUE THREAD

**Issue by jonnyhtw** [dionhaefner/veros#33]
Hi there

Firstly, thanks for sharing this code!

I can run the acc and eady models out of the box which is great but when I come to run any of global_1deg, global_4deg, north_atlantic or wave_propagation models, I get the following type of error. Is this something that you have seen before?

(my_root) clim01|Tue Jan 30|00:08:52|veros-run> cd global_1deg/
(my_root) clim01|Tue Jan 30|00:08:56|global_1deg> python global_one_degree.py
/scale_akl_persistent/filesets/home/williamsjh/veros/veros/core/numerics.py:10: UserWarning: Special OpenCL implementations could not be imported
  warnings.warn("Special OpenCL implementations could not be imported")
Traceback (most recent call last):
  File "global_one_degree.py", line 10, in <module>
    DATA_FILES = veros.tools.get_assets("global_1deg", os.path.join(BASE_PATH, "assets.yml"))
  File "/scale_akl_persistent/filesets/home/williamsjh/veros/veros/tools/assets.py", line 43, in get_assets
    return {key: get_asset(val["url"], val.get("md5", None)) for key, val in assets.items()}
  File "/scale_akl_persistent/filesets/home/williamsjh/veros/veros/tools/assets.py", line 43, in <dictcomp>
    return {key: get_asset(val["url"], val.get("md5", None)) for key, val in assets.items()}
  File "/scale_akl_persistent/filesets/home/williamsjh/veros/veros/tools/assets.py", line 36, in get_asset
    _download_file(url, target_path)
  File "/scale_akl_persistent/filesets/home/williamsjh/veros/veros/tools/assets.py", line 48, in _download_file
    with requests.get(url, stream=True, timeout=timeout) as response:
AttributeError: __exit__
(my_root) clim01|Tue Jan 30|00:09:02|global_1deg>

I have run wget on the source file for this example and it is there.

Thanks for any ideas, I'm a bit stuck!

Jonny

**Comment by dionhaefner** [comment]
Using `requests.get` as a context manager was apparently implemented quite recently. Fix should be

```bash
pip install requests -U
```

Thanks for raising this issue, and I will add a version requirement to `setup.py`.

By the way, unless you have a lot of memory and even more patience, I wouldn't recommend you to run the larger setups without using Bohrium. `global_4deg` runs very comfortably on NumPy, though.

**Comment by jonnyhtw** [comment]
Hi there

Thanks a lot for that! The error I was getting was on my work Linux machine. I've also tried it on my personal Mac and it works fine there. My personal Mac does have 'requests' installed it seems! 

You are correct regarding the calculation speed of the larger setups!

I will try your suggested fix tomorrow at work.

Many thanks!

Jonny

**Comment by jonnyhtw** [comment]
... Oh and by the way, the version of requests on my personal Mac is 2.18.4 which fits with your diagnosis above!

Cheers

Jonny

**Comment by jonnyhtw** [comment]
Oh just FYI, I am running the global_1deg model now with bohrium but got this error initially...

`libbh_filter_bcexp.so: cannot open shared object file: No such file or directory`

To get around this I had to add this to my $PATH manually...

`export PATH=~/miniconda2//pkgs/bohrium-v0.8.9-np113py27_145/lib/:$PATH`

I'm not sure if this is something that you'd expect. Anyway, just FYI.

Cheers

Jonny

**Comment by dionhaefner** [comment]
Interesting. I haven't used Anaconda in a while. I will test and raise an issue in Bohrium.

**Comment by jonnyhtw** [comment]
Hmm I just tried opening another terminal and I think it's working now. I'll let you know how I get on! I got this message when activating the env, which is good!

`clim01|Thu Feb 01|21:35:33|global_1deg> source activate my_root
setting BH_CONFIG to /home/williamsjh/.conda/envs/my_root/etc/bohrium/config.ini`

Cheers
