### ISSUE TITLE
Veros + Bohrium on GPU - RuntimeError

### ISSUE THREAD

**Issue by nutrik** [dionhaefner/veros#42]
Hi Dion,

I cannot make Veros run on GPU.
It seems like a problem with compilation of TDMA  solver.
Veros and Bohrium versions are up to date, i.e. cloned 1 day and 6 days ago, respectively.

**Run script:**
#!/bin/bash -l

export BH_STACK=opencl
veros-resubmit -i wp.05deg.cah -n 50 -l 31104000 -c "python wave_propagation.py -b bohrium -v debug" --callback "veros_gpu_run.sh"

**Command line output:**

Current iteration: 1
stopping integration at iteration 1
Waiting for lock wp.05deg.cah.0000.restart.h5 to be released
Timing summary:
 setup time               = 74.21s
 main loop time           = 1.24s
     momentum             = 0.67s
       pressure           = 0.00s
       friction           = 0.40s
     thermodynamics       = 0.00s
       lateral mixing     = 0.00s
       vertical mixing    = 0.00s
       equation of state  = 0.00s
     EKE                  = 0.04s
     IDEMIX               = 0.00s
     TKE                  = 0.51s
 diagnostics and I/O      = 0.00s
Traceback (most recent call last):
  File "wave_propagation.py", line 413, in <module>
    run()
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/tools/cli.py", line 49, in wrapped
    run(*args, **kwargs)
  File "wave_propagation.py", line 409, in run
    simulation.run()
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/veros.py", line 267, in run
    momentum.momentum(self)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/decorators.py", line 50, in veros_method_wrapper
    res = function(*args, **kwargs)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/core/momentum.py", line 76, in momentum
    friction.implicit_vert_friction(vs)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/decorators.py", line 50, in veros_method_wrapper
    res = function(*args, **kwargs)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/core/friction.py", line 82, in implicit_vert_friction
    res, mask = utilities.solve_implicit(vs, kss, a_tri, b_tri, c_tri, d_tri, b_edge=b_tri_edge)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/decorators.py", line 50, in veros_method_wrapper
    res = function(*args, **kwargs)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/core/utilities.py", line 52, in solve_implicit
    return solve_tridiag(vs, a_tri, b_tri, c_tri, d_tri), water_mask
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/decorators.py", line 50, in veros_method_wrapper
    res = function(*args, **kwargs)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/core/numerics.py", line 257, in solve_tridiag
    return tdma_opencl.tdma(a, b, c, d)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/core/special/tdma_opencl.py", line 58, in tdma
    prg = compile_tdma(ret.shape[-1], bh.interop_pyopencl.type_np2opencl_str(a.dtype))
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/core/special/tdma_opencl.py", line 35, in compile_tdma
    """.format(sys_depth=sys_depth, dtype=dtype)
ValueError: Unknown format code 'd' for object of type 'str'
Traceback (most recent call last):
  File "/groups/ocean/software/veros/inst26012018/bin/veros-resubmit", line 11, in <module>
    load_entry_point('veros', 'console_scripts', 'veros-resubmit')()
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/groups/ocean/software/python/gcc/2.7.14/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/cli/veros_resubmit.py", line 80, in cli
    resubmit(*args, **kwargs)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/cli/veros_resubmit.py", line 60, in resubmit
    call_veros(veros_cmd, identifier, current_n, length_per_run)
  File "/lustre/hpc/ocean/software/veros/repo26012018/veros/cli/veros_resubmit.py", line 46, in call_veros
    raise RuntimeError("Run {} failed, exiting".format(n))
RuntimeError: Run 0 failed, exiting

**Comment by dionhaefner** [comment]
This is fixed in the `fix-tests-again` branch. I recently encountered some problems with Bohrium, though, so you might have to downgrade if it crashes with an OpenCL error:

https://github.com/bh107/bohrium/issues/514

**Comment by nutrik** [comment]
I just thought you have already included OpenCL fix in the master branch :) 
It works now! Thanks!

**Comment by dionhaefner** [comment]
Great!
